name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build direct du Dockerfile (comme ton docker-compose)
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: synflow:test      
      - name: Cleanup & create directories
        run: |
          for d in comparisons input output uploads; do
            if [ -f "data/$d" ]; then
              echo "Removing file data/$d"
              rm -f "data/$d"
            fi 
            if [ -d "data/$d" ]; then
              echo "Removing directory data/$d"
              rm -rf "data/$d"
            fi
 
            echo "Creating directory data/$d"
            mkdir -p "data/$d"
          done


      # Test docker-compose (build + up)
      - name: Test docker-compose
        run: |
          docker compose version
          docker compose build
          docker compose up -d
          docker compose ps

      # Optionnel : test que le conteneur r√©pond bien
      - name: Wait for app to start
        run: |
          sleep 5
          curl -I http://localhost:8080 || exit 1

